files:
  - source: /docs/EN/**/*.md
    translation: /docs/CROWDIN/%two_letters_code%/**/%original_file_name%
  - source: /docs/EN/**/*.rst
    translation: /docs/CROWDIN/%two_letters_code%/**/%original_file_name%
  - source: /docs/EN/images/**/*
    translation: /docs/CROWDIN/%two_letters_code%/images/**/%original_file_name%
