# Project information
site_name: TrioDocs
site_description: Documentation of Trio, an Automated Insulin Delivery system for iOS.
site_url: https://docs.diy-trio.org/
site_author: Trio Community
use_directory_urls: !ENV [CHECK_BROKEN_LINKS, True]

# GitHub Repository
repo_name: nightscout/trio-docs
repo_url: https://github.com/nightscout/trio-docs/
edit_uri: edit/dev/docs/

copyright: Trio Community

theme:
  name: material
  language: en
  custom_dir: overrides
  logo: assets/images/trio-logo.png
  favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/brightness-auto
        name: Switch to auto (use System Preferences)
  features:
    - announce.dismiss
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow

plugins:
  - open-in-new-tab
  - macros
  - exporter:
      formats:
        pdf:
          enabled: !ENV [MKDOCS_EXPORTER_PDF, false]
          concurrency: 16
          stylesheets:
            - docs/assets/stylesheets/pdf.scss
          covers:
            front: docs/assets/templates/covers/front.html.j2
            # back: docs/assets/templates/covers/back.html.j2
          aggregator:
            enabled: true
            output: trio-docs.pdf
            covers: limits
      buttons:
        - title: Download Page as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes
  - htmlproofer:
      enabled: !ENV [CHECK_BROKEN_LINKS, False]
      raise_error_after_finish: true
  - unused_files:
      enabled: !ENV [CHECK_UNUSED_FILES, False]
      strict: true
      excluded_files:
        - back.html.j2
        - background.png
        - CNAME
        - .DS_Store
        - extra.css
        - favicon.ico
        - front.html.j2
        - .keep
        - mathjax.js
        - mkdocs-exporter.js
        - pdf.scss
        - primary_color.css
        - trio-docs.pdf
  - search

extra_css:
  - assets/stylesheets/primary_color.css
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/mathjax.js
  - assets/javascripts/mkdocs-exporter.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.9.1/mermaid.min.js

# Customizations
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nightscout/Trio
      name: Trio on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/FnwFEFUwXE
      name: Trio on Discord
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/diytrio
      name: Trio on Facebook
  version: 0.2.1

watch:
  - includes

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append:
        - includes/glossary.txt
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
      permalink_title: Link to this section for reference
      title: On this Page
      toc_depth: 3

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: warn
    absolute_links: info
    unrecognized_links: info

not_in_nav: |
  Analyze/EvaluateBasal.md
  Analyze/EvaluateCR.md
  Getting-Started/cgm.md
  settings/loop.md
  settings/configuration/preferences/statistics.md
  settings/devices/pump.md

# Navigation (Page tree)
nav:
  - Overview:
      - TODO
  - Usage:
      - TODO
  - Installation and Update:
      - Requirements:
          - Compatible Devices:
              - TODO
      - Build with Mac:
          - TODO
      - Build with Browser:
          - TODO
      - Upgrade:
          - TODO
      - Companion Apps:
          - TODO
  - Configuration:
      - Trio Settings:
          - Devices:
              - TODO
          - Therapy:
              - TODO
          - Algorithm:
              - TODO
          - Features:
              - TODO
          - Notfications:
              - TODO
          - Services:
              - Nightscout:
                  - TODO
              - Tidepool:
                  - TODO
              - Apple Health:
                  - TODO
  - Help:
      - FAQs: ./help/faq.md
      - Glossary: ./help/glossary.md
      - Submit an Issue: https://github.com/nightscout/trio-docs/issues/new/choose
      - Translate: ./help/translate.md
      - Support Communities:
          - Facebook: https://www.facebook.com/groups/diytrio
          - Discord: https://discord.gg/FnwFEFUwXE
  - 0.2.x:
      - Home: ./0.2.x/index.md
      - Overview:
          - Introduction: ./0.2.x/Getting-Started/Overview.md
          - App Overview: ./0.2.x/operate/interface.md
          - New User Guide: ./0.2.x/Setup/New-User-Setup.md
          - Coming from Other AID Systems: ./0.2.x/Configuration/transition-qa.md
          - Common Issues: ./0.2.x/operate/troubleshoot.md
          - Device Compatibility:
              - iPhones & Watches: ./0.2.x/Getting-Started/iphone.md
              - Pumps: ./0.2.x/Getting-Started/pump.md
              - CGMs: ./0.2.x/settings/devices/cgm.md
      - Build/Update Trio:
          - Build Instructions: ./0.2.x/operate/build.md
          - Customizations: ./0.2.x/operate/customize.md
      - User Settings:
          - Trio Main Preferences: ./0.2.x/settings/configuration/preferences/trio.md
          - Pump, CGM, Watch: ./0.2.x/Configuration/Devices.md
          - Additional Pump Settings: ./0.2.x/settings/configuration/pumpsettings.md
          - Basal: ./0.2.x/settings/configuration/basalprofile.md
          - ISF: ./0.2.x/settings/configuration/insulinsensitivities.md
          - CR: ./0.2.x/settings/configuration/carbratios.md
          - Target Glucose: ./0.2.x/settings/configuration/targetglucose.md
          - Main Settings: ./0.2.x/settings/configuration/preferences/mainsettings.md
          - SMB & UAM: ./0.2.x/settings/configuration/concepts/smb-uam.md
          - Close the Loop: ./0.2.x/Configuration/Configure.md
      - Optional Settings:
          - Apple Health: ./0.2.x/settings/services/applehealth.md
          - FPU: ./0.2.x/settings/services/fatprotein.md
          - Nightscout: ./0.2.x/settings/services/nightscout.md
          - Notifications: ./0.2.x/settings/services/notifications.md
          - SMB Settings: ./0.2.x/settings/configuration/preferences/smbsettings.md
          - Temp Targets: ./0.2.x/operate/temptarget.md
      - Advanced Settings:
          - Autotune: ./0.2.x/settings/configuration/autotune.md
          - Dynamic Settings: ./0.2.x/settings/configuration/concepts/autosens-dynamic.md
          - Sigmoid: ./0.2.x/settings/configuration/concepts/sigmoid.md
          - Dynamic Settings Explained: ./0.2.x/settings/configuration/preferences/dynamicsettings.md
          - Other Settings: ./0.2.x/settings/configuration/preferences/othersettings.md
          - Sensitivity Settings: ./0.2.x/settings/configuration/preferences/targetsettings.md
      - Resources:
          - Citations: ./0.2.x/resources/citations.md
          - Translation: ./0.2.x/resources/translate.md
          - TrioDocs PDF: ./0.2.x/trio-docs.pdf
