# Project information
site_name: TrioDocs
site_description: Documentation of Trio, an Automated Insulin Delivery system for iOS.
site_url: https://docs.diy-trio.org/
site_author: Trio Community
use_directory_urls: !ENV [CHECK_BROKEN_LINKS, True]

# GitHub Repository
repo_name: nightscout/trio-docs
repo_url: https://github.com/nightscout/trio-docs/
edit_uri: edit/dev/docs/

copyright: Trio Community

theme:
  name: material
  language: en
  custom_dir: overrides
  logo: assets/images/trio-logo.png
  favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/brightness-auto
        name: Switch to auto (use System Preferences)
  features:
    - announce.dismiss
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow

plugins:
  - open-in-new-tab
  - macros
  - exporter:
      formats:
        pdf:
          enabled: !ENV [MKDOCS_EXPORTER_PDF, false]
          concurrency: 16
          stylesheets:
            - docs/assets/stylesheets/pdf.scss
          covers:
            front: docs/assets/templates/covers/front.html.j2
            # back: docs/assets/templates/covers/back.html.j2
          aggregator:
            enabled: true
            output: trio-docs.pdf
            covers: limits
      buttons:
        - title: Download Page as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes
  - htmlproofer:
      enabled: !ENV [CHECK_BROKEN_LINKS, False]
      raise_error_after_finish: true
  - include-markdown:
      start: <!--include-markdown-start-->
      end: <!--include-markdown-end-->
  - unused_files:
      enabled: !ENV [CHECK_UNUSED_FILES, False]
      strict: true
      excluded_files:
        - back.html.j2
        - background.png
        - CNAME
        - .DS_Store
        - extra.css
        - favicon.ico
        - front.html.j2
        - .keep
        - mathjax.js
        - mkdocs-exporter.js
        - pdf.scss
        - primary_color.css
        - trio-docs.pdf
  - search

extra_css:
  - assets/stylesheets/primary_color.css
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/mathjax.js
  - assets/javascripts/mkdocs-exporter.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.9.1/mermaid.min.js

# Customizations
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nightscout/Trio
      name: Trio on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/FnwFEFUwXE
      name: Trio on Discord
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/diytrio
      name: Trio on Facebook
  version: 0.2.1

watch:
  - includes

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append:
        - includes/glossary.txt
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
      permalink_title: Link to this section for reference
      title: On this Page
      toc_depth: 3

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: warn
    absolute_links: info
    unrecognized_links: info

not_in_nav: |
  0.2.x/Analyze/EvaluateBasal.md
  0.2.x/Analyze/EvaluateCR.md
  0.2.x/Getting-Started/cgm.md
  0.2.x/settings/loop.md
  0.2.x/settings/configuration/preferences/statistics.md
  0.2.x/settings/devices/pump.md
  Analyze/EvaluateBasal.md
  Analyze/EvaluateCR.md
  configuration/Configure.md
  Getting-Started/cgm.md
  configuration/CompatibleDevices.md
  configuration/configure.md
  configuration/transition-qa.md
  includes/version-compatibility-matrix.md
  includes/supported-iphones.md
  operate/build.md
  operate/customize.md
  resources/citations.md
  settings/configuration/preferences/statistics.md
  settings/devices/pump.md
  settings/configuration/autotune.md
  settings/configuration/basalprofile.md
  settings/configuration/targetglucose.md
  settings/configuration/insulinsensitivities.md
  settings/configuration/target_glucose.md
  settings/configuration/concepts/sigmoid.md
  settings/configuration/concepts/smb-uam.md
  settings/configuration/preferences/mainsettings.md
  settings/configuration/preferences/othersettings.md
  settings/configuration/preferences/targetsettings.md
  settings/configuration/preferences/trio.md
  settings/loop.md
  settings/services/fatprotein.md
  usage/statistics.md

# Navigation (Page tree)
nav:
  - index.md
  - Overview:
      - Definition: overview/definition.md
      #- Use Cases ✏️: overview/use_cases.md
      #- Comparison with Other Systems ✏️: overview/comparison.md
      #- Advantages ✏️: overview/advantages.md
      #- Disadvantages ✏️: overview/disadvantages.md
      #- Safety ✏️: overview/safety.md
  - Usage:
      - usage/index.md
      - User Interface: usage/interface.md
      #- Temporary Targets ✏️: usage/temptarget.md
      #- Overrides ✏️: usage/overrides.md
  - Installation and Update:
      - install/index.md
      - Requirements:
          - Compatible Devices:
              - install/build/requirements/devices/index.md
              - Insulin Pump: install/build/requirements/devices/pump.md
              - CGM: install/build/requirements/devices/cgm.md
              - iPhone: install/build/requirements/devices/iphone.md
              - Mac ✏️: install/build/requirements/devices/mac.md # TODO
              - Compatibility Matrix ✏️: install/build/requirements/devices/compatibility-matrix.md # TODO
          - Apple Developer Account: install/build/requirements/apple-developer.md
      - Build with Mac:
          - Mac Build Overview: install/build/mac/overview.md
          - Prepare your Computer: install/build/mac/computer.md
          - Prepare your iPhone: install/build/mac/iphone.md
          - Set Up Xcode: install/build/mac/xcode-setup.md
          - Build Select Script ✏️: install/build/mac/build-select-script.md
          - Build Trio with Xcode: install/build/mac/build.md
          - Build Errors: install/build/mac/build-errors.md
          - Update Trio with Xcode: install/build/mac/update.md
      - Build with Browser:
          - Browser Build Overview ✏️: install/build/browser/browser-build-overview.md
          - Create GitHub Account ✏️: install/build/browser/create-github-account.md
          - Collect Secrets ✏️: install/build/browser/collect-secrets.md
          - Fork and Prepare your Trio Repository✏️: install/build/browser/fork-prepare-repo.md
          - GitHub Actions:
              - Validate Secrets ✏️: install/build/browser/actions/validate-secrets.md
              - Add Identifiers ✏️: install/build/browser/actions/add-identifiers.md
              - Prepare App ✏️: install/build/browser/actions/prepare-app.md
              - Generate Certificates ✏️: install/build/browser/actions/generate-certificates.md
              - Build the App ✏️: install/build/browser/actions/build-app.md
          - Install Trio from TestFlight ✏️: install/build/browser/install-from-testflight.md
          - Browser Build Errors ✏️: install/build/browser/browser-build-errors.md
          - Customizations ✏️: install/build/browser/browser-customizations.md
          - Update with Browser ✏️: install/build/browser/update-with-browser.md
      - Upgrade ✏️: install/upgrade.md
      - Companion Apps:
          - install/ecosystem/index.md
          - Nightscout ✏️: install/ecosystem/nightscout-app.md
          - Loop Follow ✏️: install/ecosystem/loop-follow.md
          - XDrip4iOS ✏️: install/ecosystem/xdrip4ios.md
  - Configuration:
      - configuration/index.md
      - New User Setup Guide: configuration/new_user_setup.md
      - Trio Settings:
          - configuration/settings/index.md
          - Devices:
              - configuration/settings/devices/index.md
              - Insulin Pump: configuration/settings/devices/pump.md
              - Continuous Glucose Monitor: configuration/settings/devices/cgm.md
              - Smart Watch: configuration/settings/devices/smart_watch.md
          - Therapy:
              - configuration/settings/therapy/index.md
              - Units and Limits: configuration/settings/therapy/units_limits.md
              - Basal Rates: configuration/settings/therapy/basal_rates.md
              - Insulin Sensitivities: configuration/settings/therapy/isf.md
              - Carb Ratios: configuration/settings/therapy/carb_ratios.md
              - Glucose Targets: configuration/settings/therapy/glucose_targets.md
          - Algorithm:
              - configuration/settings/algorithm/index.md
              - Autosens: configuration/settings/algorithm/autosens.md
              - Super Micro Bolus (SMB): configuration/settings/algorithm/smb_settings.md
              - Dynamic Settings: configuration/settings/algorithm/dynamic_settings.md
              - Target Behavior: configuration/settings/algorithm/target_behavior.md
              - Additionals: configuration/settings/algorithm/additionals.md
          - Features:
              - configuration/settings/features/index.md
              - Bolus Calculator: configuration/settings/features/bolus_calculator.md
              - Meal Settings: configuration/settings/features/meal_settings.md
              - Shortcuts: configuration/settings/features/shortcuts.md
              - Remote Control: configuration/settings/features/remote_control.md
              - User Interface: configuration/settings/features/user_interface.md
              - App Icons: configuration/settings/features/app_icons.md
          - Notifications:
              - configuration/settings/notifications/index.md
              - Trio Notifications: configuration/settings/notifications/trio_notifications.md
              - Live Activity: configuration/settings/notifications/live_activity.md
              - Calendar Events: configuration/settings/notifications/calendar_events.md
          - Services:
              - configuration/settings/services/index.md
              - Nightscout: configuration/settings/services/nightscout.md
              - Tidepool ✏️: configuration/settings/services/tidepool.md
              - Apple Health: configuration/settings/services/apple_health.md
          - Closing The Loop: configuration/settings/closed-loop.md
  - Help:
      - FAQs: help/faq.md
      - Safety ✏️: help/safety.md
      - Glossary: help/glossary.md
      - Troubleshooting: help/troubleshoot.md
      - Submit an Issue: https://github.com/nightscout/trio-docs/issues/new/choose
      - Translate: help/translate.md
      - Support Communities:
          - Facebook: https://www.facebook.com/groups/diytrio
          - Discord: https://discord.gg/FnwFEFUwXE
  - 0.2.x:
      - Home: ./0.2.x/index.md
      - Overview:
          - Introduction: ./0.2.x/Getting-Started/Overview.md
          - App Overview: ./0.2.x/operate/interface.md
          - New User Guide: ./0.2.x/Setup/New-User-Setup.md
          - Coming from Other AID Systems: ./0.2.x/Configuration/transition-qa.md
          - Common Issues: ./0.2.x/operate/troubleshoot.md
          - Device Compatibility:
              - iPhones & Watches: ./0.2.x/Getting-Started/iphone.md
              - Pumps: ./0.2.x/Getting-Started/pump.md
              - CGMs: ./0.2.x/settings/devices/cgm.md
      - Build/Update Trio:
          - Build Instructions: ./0.2.x/operate/build.md
          - Customizations: ./0.2.x/operate/customize.md
      - User Settings:
          - Trio Main Preferences: ./0.2.x/settings/configuration/preferences/trio.md
          - Pump, CGM, Watch: ./0.2.x/Configuration/Devices.md
          - Additional Pump Settings: ./0.2.x/settings/configuration/pumpsettings.md
          - Basal: ./0.2.x/settings/configuration/basalprofile.md
          - ISF: ./0.2.x/settings/configuration/insulinsensitivities.md
          - CR: ./0.2.x/settings/configuration/carbratios.md
          - Target Glucose: ./0.2.x/settings/configuration/targetglucose.md
          - Main Settings: ./0.2.x/settings/configuration/preferences/mainsettings.md
          - SMB & UAM: ./0.2.x/settings/configuration/concepts/smb-uam.md
          - Close the Loop: ./0.2.x/Configuration/Configure.md
      - Optional Settings:
          - Apple Health: ./0.2.x/settings/services/applehealth.md
          - FPU: ./0.2.x/settings/services/fatprotein.md
          - Nightscout: ./0.2.x/settings/services/nightscout.md
          - Notifications: ./0.2.x/settings/services/notifications.md
          - SMB Settings: ./0.2.x/settings/configuration/preferences/smbsettings.md
          - Temp Targets: ./0.2.x/operate/temptarget.md
      - Advanced Settings:
          - Autotune: ./0.2.x/settings/configuration/autotune.md
          - Dynamic Settings: ./0.2.x/settings/configuration/concepts/autosens-dynamic.md
          - Sigmoid: ./0.2.x/settings/configuration/concepts/sigmoid.md
          - Dynamic Settings Explained: ./0.2.x/settings/configuration/preferences/dynamicsettings.md
          - Other Settings: ./0.2.x/settings/configuration/preferences/othersettings.md
          - Sensitivity Settings: ./0.2.x/settings/configuration/preferences/targetsettings.md
      - Resources:
          - Citations: ./0.2.x/resources/citations.md
          - Translation: ./0.2.x/resources/translate.md
#          - TrioDocs PDF: ./0.2.x/trio-docs.pdf
